version: '2.0'

services:
    postgres:
      image: lombardo/postgres-scrabble-helper
      container_name: postgres
      ports:
        - "5431:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=scrabble_helper
    scrabble-helper-api:
        image: lombardo/scrabble-helper-api
        container_name: scrabble-helper-api
        ports:
          - "18080:8080"
        depends_on:
          - postgres
        links:
          - postgres
        environment:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: scrabble_helper