version: '2.0'

services:
    postgres:
      image: 7d7efc713d11
      container_name: postgres
      ports:
        - "5431:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=scrabble_helper
    redis:
      image: lombardo/redis-scrabble-helper
      container_name: redis
      ports:
        - "6379:6379"
    scrabble-helper-api:
        image: 136871f9f15d
        container_name: scrabble-helper-api
        ports:
          - "18080:8080"
        depends_on:
          - postgres
          - redis
        links:
          - postgres
          - redis
        environment:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: scrabble_helper
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REPOSITORY_SERVICE: LOCAL 
